INSERT INTO BOARD(TITLE, CONTENT, WRITER)
VALUES('선선한 가을이 왔습니다.','다같이 단풍구경 가는건 어떨까요?','민');
INSERT INTO BOARD(TITLE, CONTENT, WRITER)
VALUES('안녕하세요','어떨까요?','민2');
INSERT INTO BOARD(TITLE, CONTENT, WRITER)
VALUES('타이틀','단풍구경 가는건 어떨까요?','민3');
INSERT INTO BOARD(TITLE, CONTENT, WRITER)
VALUES('타이틀2','가는건 어떨까요?','민4');

DELETE FROM BOARD WHERE IDX=9;